{
 "title": "Electricity",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Grid",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT inverter.output_power - home_consumption.total as grid\nFROM inverter\nJOIN home_consumption ON inverter.time = home_consumption.time\nWHERE $__timeFilter(inverter.time)\nORDER BY inverter.time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  inverter.time,\n  inverter.output_power - home_consumption.total as grid\nFROM inverter\nJOIN home_consumption ON inverter.time = home_consumption.time\nWHERE $__timeFilter(inverter.time)"
    }
   ]
  },
  {
   "title": "Inverter Output Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT output_power\nFROM inverter\nWHERE\n  $__timeFilter(time)\nORDER BY time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Inverter Output Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  output_power\nFROM inverter\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Inverter Power by Phase",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  l1_power,\n  l2_power,\n  l3_power\nFROM inverter\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Home Consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT total\nFROM home_consumption\nWHERE $__timeFilter(time)\nORDER BY time DESC \nLIMIT 1"
    }
   ]
  },
  {
   "title": "Home Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  total\nFROM home_consumption\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Home Consumption by Source",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  from_pv,\n  from_grid,\n  from_battery\nFROM home_consumption\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}