{
 "title": "Kostal",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "PV Generator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM pv_generator\nWHERE\n  $__timeFilter(time)\nORDER BY time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Inverter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM inverter\nWHERE\n  $__timeFilter(time)\nORDER BY time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Home Consumption",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM home_consumption\nWHERE\n  $__timeFilter(time)\nORDER BY time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT inverter.output_power - home_consumption.total as grid\nFROM inverter\nJOIN home_consumption ON inverter.time = home_consumption.time\nWHERE $__timeFilter(inverter.time)\nORDER BY inverter.time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "DC Input 1",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "DC Input 2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "DC Input 3",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Phase 1",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Phase 2",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Phase 3",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  }
 ]
}